language: python

branches:

services:
    - docker

python:
    - 2.6

cache: pip

before_install:
    - docker pull fedora:27

install:
    - pip install --upgrade pip
    - pip install pycodestyle tox

script:
    - tox -epep8,flake8
    - docker run -v ${TRAVIS_BUILD_DIR}:/root/src/ fedora:29 /bin/sh -c "dnf -y install freeipa-server freeipa-server-trust-ad python2-ipaserver python2-ipalib python2-mock python2-libsss_nss_idmap python2-dns tox python2-pytest; cd /root/src; tox -epy2"
